# The final executable
PROGRAM = trafficsensor.x

# The source files (*.cc)
SRCS = counter.cc trafficsensor.cc monitor.cc trafficsensor_testbench.cc

##################################
## DO NOT CHANGE ANYTHING BELOW ##
##################################

SYSTEMC = /courses/TDTS07/sw/systemc
TARGET_ARCH = linux64

LIBDIR = -L. -L.. -L$(SYSTEMC)/lib-$(TARGET_ARCH)
LIBS = -Wl,-Bstatic -lsystemc -Wl,-Bdynamic -lm -lpthread
LDFLAGS = -g

CC = g++
OPT = -O3
CFLAGS = -Wno-deprecated
EXE = $(PROGRAM)

INCDIR= -I. -I.. -I$(SYSTEMC)/include

OBJS = $(SRCS:.cc=.o)

.SUFFIXES: .cc .o .x

$(EXE): $(OBJS)
	$(CC) $(LDFLAGS) $(INCDIR) $(LIBDIR) -o $(EXE) $(OBJS) $(LIBS)

# To build the whole project we must compile each .cc file into a .o file, and
# then link all .o-files into an executable. The rule above tells the make tool
# how to link the object files into an executable. To create the object files we
# need additional rules (one for each .cc-file). For each .cc-file we add two
# lines in the make file. The first line consists of a list of one .cc file
# (corresponding to the .o-file beeing created) and possibly a list of .h-files.
# Whenever any of the files in the list has changed, the make tool will
# recompile the object file. The list should be the .cc-file beeing compiled,
# and all the .h-files that are included in that .cc-file.

trafficsensor_testbench.o: trafficsensor_testbench.cc trafficsensor.h counter.h monitor.h
	$(CC) -c $(CFLAGS) $(INCDIR) trafficsensor_testbench.cc -o trafficsensor_testbench.o

trafficsensor.o: trafficsensor.cc trafficsensor.h
	$(CC) -c $(CFLAGS) $(INCDIR) trafficsensor.cc -o trafficsensor.o

counter.o: counter.cc counter.h
	$(CC) -c $(CFLAGS) $(INCDIR) counter.cc -o counter.o

monitor.o: monitor.cc monitor.h
	$(CC) -c $(CFLAGS) $(INCDIR) monitor.cc -o monitor.o

clean:
	rm -f $(OBJS) $(EXE) *~
